version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saludtechalpes-images-service
    restart: always
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    env_file:
      - .env
    tty: true