version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saludtechalpes-data-processor-service
    restart: always
    volumes:
      - ".:/app"
    ports:
      - "3000:5000"
    env_file:
      - .env
    tty: true