apiVersion: batch/v1
kind: Job
metadata:
  name: pulsar-init
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: pulsar-init
          image: apachepulsar/pulsar:latest
          command:
            - "/bin/sh"
            - "-c"
          args:
            - >
              bin/pulsar initialize-cluster-metadata 
              --cluster cluster-a 
              --zookeeper zookeeper:2181 
              --configuration-store zookeeper:2181 
              --web-service-url http://pulsar-broker:8080 
              --broker-service-url pulsar://pulsar-broker:6650
